fun main() {
    print("Hello, nama saya" )
    println("ria riyanti")
    print("jenis kelamin" )
    println("perempuan")
    print("tempat tanggal lahir" )
    println("Bandung 19 agustus 2007")
    print("sekolah" )
    println("smkn 7 baleendah")
    print("alamat" )
    println("kp sadangsari tr 05 rw 04" )
    print("hobby")
    println("nonton")
    print("cita-cita" )
    println("fotografer")
}